// <auto-generated />
using System;
using Flight_Detection.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flight_Detection.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230925143553_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flight_Detection.Entity.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlightId"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.HasKey("FlightId");

                    b.HasIndex("RouteId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Flight_Detection.Entity.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RouteId"));

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("integer");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("integer");

                    b.HasKey("RouteId");

                    b.HasIndex("OriginCityId", "DestinationCityId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Flight_Detection.Entity.Models.Subscription", b =>
                {
                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationCityId")
                        .HasColumnType("integer");

                    b.Property<int>("OriginCityId")
                        .HasColumnType("integer");

                    b.HasIndex("AgencyId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Flight_Detection.Entity.Models.Flight", b =>
                {
                    b.HasOne("Flight_Detection.Entity.Models.Route", "Route")
                        .WithMany("Flights")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Flight_Detection.Entity.Models.Route", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
